
services:
- type: worker
  name: discord-ticket-bot
  runtime: python
  plan: starter
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python bot.py"
  envVars:
    - key: DISCORD_TOKEN
      sync: false
    - key: PYTHON_VERSION
      value: 3.11.7
